services:
  - type: web
    name: FullStackWebsite
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn FullStack_website.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-v+-99lm0wrq@#f2%*)8(69#20+$u!gs##4u(85av)(bak5g@pk
      - key: DEBUG
        value: "False"
